# Generated by Django 5.2.5 on 2025-08-31 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_date',
            field=models.DateTimeField(),
        ),
    ]
