# Generated by Django 5.2.4 on 2025-07-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='project')),
            ],
        ),
    ]
