# Generated by Django 5.2.4 on 2025-07-28 09:12

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, unique_for_date='pub_date')),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='images/articles')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
                ('is_published', models.DurationField(default=datetime.timedelta(days=30))),
                ('status', models.BooleanField(default=True)),
                ('published', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('floatfield', models.FloatField(default=1)),
                ('myfile', models.FileField(null=True, upload_to='test')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(to='post.category')),
            ],
        ),
    ]
