# Generated by Django 5.2.4 on 2025-07-27 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.DurationField(default=datetime.timedelta(days=30)),
        ),
    ]
