# Generated by Django 5.2.4 on 2025-09-01 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_article_pub_date_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 1, 19, 21, 3, 827271, tzinfo=datetime.timezone.utc)),
        ),
    ]
